ifneq (,$(filter caching_iperf,$(USEMODULE)))

USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_icmpv6_echo
# USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_ipv6_router_default

USEMODULE += netutils
USEMODULE += sema_inv
USEMODULE += sock_udp
USEMODULE += sock_tcp

USEMODULE += shell_cmds_default
USEMODULE += shell_cmd_gnrc_udp

# Routing
USEMODULE += gnrc_rpl
USEMODULE += auto_init_gnrc_rpl

USEMODULE += ps
USEMODULE += netstats_l2
USEMODULE += netstats_ipv6
USEMODULE += netstats_rpl

endif
